/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SILVESTRE Richard
 */
public class nouveaujeu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(nouveaujeu.class.getName());

    Metier jeu = new Metier();
    
    
    // Méthode pour incrémenter un chiffre (0 -> 1 ... -> 9 -> 0)
    private void incrementerLabel(javax.swing.JLabel label) {
    int valeur = Integer.parseInt(label.getText());
    valeur = (valeur + 1) % 10;
    label.setText(String.valueOf(valeur));
    }

// Méthode pour décrémenter un chiffre (0 -> 9 ... -> 1 -> 0)
    private void decrementerLabel(javax.swing.JLabel label) {
    int valeur = Integer.parseInt(label.getText());
    if (valeur == 0) valeur = 9;
    else valeur--;
    label.setText(String.valueOf(valeur));
    }
    /**
     * Creates new form nouveaujeu
     */
    public nouveaujeu() {
        initComponents();
    up_chiffre_1.addActionListener(e -> incrementerLabel(texte_chiffre_0)); // [cite: 40, 44]
    up_chiffre_2.addActionListener(e -> incrementerLabel(texte_chiffre_1)); // [cite: 41, 45]
    up_chiffre_3.addActionListener(e -> incrementerLabel(texte_chiffre_2)); // [cite: 42, 46]
    up_chiffre_4.addActionListener(e -> incrementerLabel(texte_chiffre_3)); // [cite: 43, 47]

    // Boutons DOWN
    down_chiffre_1.addActionListener(e -> decrementerLabel(texte_chiffre_0)); // [cite: 48]
    down_chiffre_2.addActionListener(e -> decrementerLabel(texte_chiffre_1)); // [cite: 49]
    down_chiffre_3.addActionListener(e -> decrementerLabel(texte_chiffre_2)); // [cite: 50]
    down_chiffre_4.addActionListener(e -> decrementerLabel(texte_chiffre_3)); // [cite: 51]

    bouton_tester.addActionListener(e -> {    
            
    // 1. Récupérer la proposition du joueur
    int[] proposition = new int[4];
    proposition[0] = Integer.parseInt(texte_chiffre_0.getText());
    proposition[1] = Integer.parseInt(texte_chiffre_1.getText());
    proposition[2] = Integer.parseInt(texte_chiffre_2.getText());
    proposition[3] = Integer.parseInt(texte_chiffre_3.getText());

    // 2. Vérifier via la classe Metier
    int[] resultats = jeu.verifierCombinaison(proposition);

    // 3. Mettre à jour l'interface avec les résultats exacts
    texte_nb_chiffres_exacts.setText(String.valueOf(resultats[0])); // [cite: 54]
    texte_nb_chiffres_haut.setText(String.valueOf(resultats[1]));   // [cite: 56]
    texte_nb_chiffres_bas.setText(String.valueOf(resultats[2]));    // [cite: 58]

    // 4. Mettre à jour les tentatives (ex: "1 sur 5")
    texte_tentatives.setText(jeu.getTentatives() + " sur " + jeu.MAX_TENTATIVES); // [cite: 60]

    // 5. Gestion de fin de partie (Gagné ou Perdu)
    if (resultats[0] == 4) {
        javax.swing.JOptionPane.showMessageDialog(this, "Bravo ! Vous avez trouvé le code !");
        bouton_tester.setEnabled(false); // Désactive le bouton
    } else if (jeu.estPerdu()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Perdu ! Vous avez épuisé vos 5 tentatives.");
        bouton_tester.setEnabled(false);
    }
});
    
    bouton_recommencer.addActionListener(e -> {
    // 1. Réinitialiser le métier
    jeu.genererCombinaison();

    // 2. Remettre les affichages à zéro
    texte_chiffre_0.setText("0");
    texte_chiffre_1.setText("0");
    texte_chiffre_2.setText("0");
    texte_chiffre_3.setText("0");
    
    texte_nb_chiffres_exacts.setText("0");
    texte_nb_chiffres_haut.setText("0");
    texte_nb_chiffres_bas.setText("0");
    texte_tentatives.setText("0 sur 5");

    // 3. Réactiver le bouton tester
    bouton_tester.setEnabled(true);
        });
    bouton_recommencer.addActionListener(e -> {
    // 1. Réinitialiser le métier
    jeu.genererCombinaison();

    // 2. Remettre les affichages à zéro
    texte_chiffre_0.setText("0");
    texte_chiffre_1.setText("0");
    texte_chiffre_2.setText("0");
    texte_chiffre_3.setText("0");
    
    texte_nb_chiffres_exacts.setText("0");
    texte_nb_chiffres_haut.setText("0");
    texte_nb_chiffres_bas.setText("0");
    texte_tentatives.setText("0 sur 5");

    // 3. Réactiver le bouton tester
    bouton_tester.setEnabled(true);
});
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_tester = new javax.swing.JButton();
        texte_score = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Trouvez le bon code en moins de 5 tentatives !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.setAlignmentY(0.0F);
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 50, 30));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.setAlignmentY(0.0F);
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 30));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.setAlignmentY(0.0F);
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 50, 30));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.setAlignmentY(0.0F);
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 50, 30));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.setAlignmentY(0.0F);
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 183, 50, 30));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.setAlignmentY(0.0F);
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 183, 50, 30));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.setAlignmentY(0.0F);
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 183, 50, 30));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.setAlignmentY(0.0F);
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 183, 50, 30));

                        texte_chiffre_0.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
                        texte_chiffre_0.setText("0");
                        texte_chiffre_0.setAlignmentY(0.0F);
                        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 30, 85));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
                        texte_chiffre_1.setText("0");
                        texte_chiffre_1.setAlignmentY(0.0F);
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 30, 80));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
                        texte_chiffre_2.setText("0");
                        texte_chiffre_2.setAlignmentY(0.0F);
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 40, 85));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
                        texte_chiffre_3.setText("0");
                        texte_chiffre_3.setAlignmentY(0.0F);
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 40, 85));

                        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exact :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

                        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

                        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 10, -1));

                        texte_nb_chiffres_haut.setText("0");
                        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

                        texte_tentatives.setText("Tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 226, -1, -1));

                        bouton_tester.setText("Tester");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 121, -1, -1));

                        texte_score.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
                        texte_score.setText("0 sur 5");
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 269, -1, -1));

                        bouton_recommencer.setText("Recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
     }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
      }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new nouveaujeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
